import { Question } from '@/store/useQuizStore';

const COLORS = ['bg-red-500', 'bg-blue-500', 'bg-yellow-500', 'bg-green-500'];

export const ADVANCED_AI_QUESTIONS: Question[] = [
  {
    id: 'ai-advanced-1',
    type: 'choice',
    text: 'A larger context window mainly helps because it can...',
    options: [
      { id: 'o1', text: 'Guarantee the model remembers everything perfectly', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'Use more supplied material, while still needing prioritisation', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'Remove the need for retrieval or source selection', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Stop hallucinations in high-risk tasks', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 35,
  },
  {
    id: 'ai-advanced-2',
    type: 'choice',
    text: 'When is RAG usually a better first move than fine-tuning?',
    options: [
      { id: 'o1', text: 'When the answer depends on changing documents or policies', color: COLORS[0], isCorrect: true },
      { id: 'o2', text: 'When you want the model to permanently memorise secrets', color: COLORS[1], isCorrect: false },
      { id: 'o3', text: 'When the base model cannot follow instructions at all', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'When no source material exists', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 35,
  },
  {
    id: 'ai-advanced-3',
    type: 'choice',
    text: 'A weak retrieval setup most often fails because it...',
    options: [
      { id: 'o1', text: 'Uses too many colours in the interface', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'Retrieves plausible but irrelevant or incomplete context', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'Forces the model to answer in full sentences', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Prevents users from asking follow-up questions', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-4',
    type: 'choice',
    text: 'What is the strongest use of evals in a production AI workflow?',
    options: [
      { id: 'o1', text: 'Proving the model will never make mistakes', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'Checking behaviour against representative cases over time', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'Replacing all human review', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Making prompts longer so they feel complete', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 35,
  },
  {
    id: 'ai-advanced-5',
    type: 'choice',
    text: 'Temperature is best understood as a control for...',
    options: [
      { id: 'o1', text: 'The factuality of the training data', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'How deterministic or varied the next-token choices are', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'The size of the model context window', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Whether the model can browse the web', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-6',
    type: 'choice',
    text: 'Prompt injection is dangerous because external content can...',
    options: [
      { id: 'o1', text: 'Make the model output shorter than expected', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'Attempt to override instructions or misuse connected tools', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'Only affect image generation models', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Increase token costs but not behaviour risk', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 35,
  },
  {
    id: 'ai-advanced-7',
    type: 'choice',
    text: 'Embeddings are most useful when you need to...',
    options: [
      { id: 'o1', text: 'Compare meaning or similarity across text chunks', color: COLORS[0], isCorrect: true },
      { id: 'o2', text: 'Encrypt private data before sending it to a model', color: COLORS[1], isCorrect: false },
      { id: 'o3', text: 'Guarantee citations are legally approved', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Turn every answer into JSON automatically', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-8',
    type: 'choice',
    text: 'Structured outputs are valuable because they...',
    options: [
      { id: 'o1', text: 'Make the model smarter about the topic', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'Make downstream automation easier to parse and validate', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'Remove the need to handle errors', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Always reduce the number of tokens used', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-9',
    type: 'choice',
    text: 'A good agentic workflow should give the model tool access only when...',
    options: [
      { id: 'o1', text: 'The task has clear bounds, permissions, and recovery paths', color: COLORS[0], isCorrect: true },
      { id: 'o2', text: 'The user wants the demo to look impressive', color: COLORS[1], isCorrect: false },
      { id: 'o3', text: 'The task is vague and nobody owns the result', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'The model says it is confident', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 35,
  },
  {
    id: 'ai-advanced-10',
    type: 'choice',
    text: 'What is the main risk of asking a model for hidden chain-of-thought?',
    options: [
      { id: 'o1', text: 'It may produce verbose rationales without improving reliability', color: COLORS[0], isCorrect: true },
      { id: 'o2', text: 'It makes the context window smaller', color: COLORS[1], isCorrect: false },
      { id: 'o3', text: 'It disables structured outputs', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'It prevents the model from using examples', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 35,
  },
  {
    id: 'ai-advanced-11',
    type: 'choice',
    text: 'For client-facing work, the safest source policy is usually...',
    options: [
      { id: 'o1', text: 'Use any source the model names confidently', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'Prefer verified sources and show the evidence trail', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'Use no sources so the deck is cleaner', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Use only sources from the first search result', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-12',
    type: 'choice',
    text: 'A model version change can break a workflow because...',
    options: [
      { id: 'o1', text: 'Outputs, formatting, tool use, or refusal behaviour can shift', color: COLORS[0], isCorrect: true },
      { id: 'o2', text: 'All prompts stop working immediately', color: COLORS[1], isCorrect: false },
      { id: 'o3', text: 'Context windows always become smaller', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Previous outputs are deleted', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 35,
  },
  {
    id: 'ai-advanced-13',
    type: 'choice',
    text: 'In AI workflows, human review is most important when...',
    options: [
      { id: 'o1', text: 'The output affects spend, advice, reputation, or policy', color: COLORS[0], isCorrect: true },
      { id: 'o2', text: 'The output is only used to format a meeting agenda', color: COLORS[1], isCorrect: false },
      { id: 'o3', text: 'The model used a short answer', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'The prompt included a role', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-14',
    type: 'choice',
    text: 'The best reason to use few-shot examples is to...',
    options: [
      { id: 'o1', text: 'Demonstrate the desired pattern and quality bar', color: COLORS[0], isCorrect: true },
      { id: 'o2', text: 'Make the model ignore all instructions', color: COLORS[1], isCorrect: false },
      { id: 'o3', text: 'Guarantee factual accuracy', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Replace evaluation and review', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-15',
    type: 'choice',
    text: 'A strong AI privacy habit for agency work is to...',
    options: [
      { id: 'o1', text: 'Paste sensitive client data into any useful tool', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'Use approved tools and minimise unnecessary client data', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'Rely on prompts to delete confidential information', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Assume public demos are safe for private data', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-16',
    type: 'choice',
    text: 'Overfitting in a model or workflow usually shows up as...',
    options: [
      { id: 'o1', text: 'Great performance on known examples, weaker generalisation', color: COLORS[0], isCorrect: true },
      { id: 'o2', text: 'The model refusing every prompt', color: COLORS[1], isCorrect: false },
      { id: 'o3', text: 'Lower compute cost with no trade-offs', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Better performance on every future task', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-17',
    type: 'choice',
    text: 'A good red-team test for an AI assistant tries to...',
    options: [
      { id: 'o1', text: 'Find realistic ways the workflow could fail or be misused', color: COLORS[0], isCorrect: true },
      { id: 'o2', text: 'Make the interface look more dramatic', color: COLORS[1], isCorrect: false },
      { id: 'o3', text: 'Confirm only the happy path', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Avoid edge cases so the tool feels stable', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-18',
    type: 'choice',
    text: 'When comparing models, the most useful benchmark is...',
    options: [
      { id: 'o1', text: 'A generic leaderboard only', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'A representative set of your real tasks and constraints', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'The model with the longest name', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'The model that writes the longest answer', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-19',
    type: 'choice',
    text: 'What is the most useful way to handle uncertainty in AI output?',
    options: [
      { id: 'o1', text: 'Suppress it so the answer feels confident', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'State assumptions, confidence, gaps, and next checks', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'Ask for the same answer in a different tone', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'Treat every caveat as a failure', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 30,
  },
  {
    id: 'ai-advanced-20',
    type: 'choice',
    text: 'The best AI workflow usually optimises for...',
    options: [
      { id: 'o1', text: 'Impressive demos over repeatable quality', color: COLORS[0], isCorrect: false },
      { id: 'o2', text: 'Clear inputs, useful outputs, evidence, checks, and ownership', color: COLORS[1], isCorrect: true },
      { id: 'o3', text: 'The fewest possible human touchpoints', color: COLORS[2], isCorrect: false },
      { id: 'o4', text: 'The longest prompt and most tools', color: COLORS[3], isCorrect: false },
    ],
    timeLimit: 35,
  },
];
