import { Quiz } from '@/store/useQuizStore';

const COLORS = ['bg-red-500', 'bg-blue-500', 'bg-yellow-500', 'bg-green-500'];

export const YOUNGSHAND_WORKSHOP_PACKS: Quiz[] = [
  {
    id: 'youngshand-prove-it-sprint',
    title: 'YoungShand Prove-It Sprint',
    description: 'A live workshop flow for turning AI from a quick answer machine into a better evidence and decision support tool.',
    createdAt: '2026-05-20T00:00:00.000Z',
    questions: [
      {
        id: 'pi-open-1',
        type: 'open',
        text: 'Where does AI still feel risky or hard to trust in YoungShand work?',
        facilitatorNote: 'Use this as the room warm-up. Look for repeated themes: source confidence, category context, media spend, client sensitivity, and review ownership.',
        placeholder: 'Example: first-pass category research, budget rationale, audience insight, competitor scan...',
        options: [],
        timeLimit: 90,
      },
      {
        id: 'pi-choice-1',
        type: 'choice',
        text: 'A useful proof layer for an AI recommendation should mostly...',
        facilitatorNote: 'Reinforce that AI output needs a trail: sources, assumptions, criteria, and a clear handoff to human judgement.',
        options: [
          { id: 'o1', text: 'Sound confident and use polished wording', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Show sources, assumptions, and decision criteria', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Avoid disagreement so the answer is clean', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Make the recommendation as short as possible', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-open-2',
        type: 'open',
        text: 'Pick a client or category decision that AI could help prove this week.',
        facilitatorNote: 'Ask people to make it specific. Good submissions sound like a decision question, not a generic topic.',
        placeholder: 'For [client/category], should we choose [option A] or [option B] because...',
        options: [],
        timeLimit: 120,
      },
      {
        id: 'pi-choice-2',
        type: 'choice',
        text: 'If an AI answer gives one confident recommendation with no assumptions, what is the next move?',
        facilitatorNote: 'This is the core behaviour shift: challenge the output before it enters client or planning work.',
        options: [
          { id: 'o1', text: 'Ask for evidence, assumptions, and alternatives', color: COLORS[0], isCorrect: true },
          { id: 'o2', text: 'Paste it into the deck and tighten the wording', color: COLORS[1], isCorrect: false },
          { id: 'o3', text: 'Ask the same question again until it agrees', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Remove all caveats so the answer feels decisive', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-open-3',
        type: 'open',
        text: 'Rewrite your decision as a stronger AI prompt.',
        facilitatorNote: 'Have them include role, context, evidence requirements, decision criteria, and output format. Pull two examples up and improve them live.',
        placeholder: 'Act as... Context... Compare... Use evidence from... Return a table with...',
        options: [],
        timeLimit: 180,
      },
      {
        id: 'pi-choice-3',
        type: 'choice',
        text: 'The best first AI pilot for an agency team is usually...',
        facilitatorNote: 'Push toward low-risk, repeatable work first. A good pilot should be visible enough to learn from, but not dangerous if it fails.',
        options: [
          { id: 'o1', text: 'The most complex client strategy problem available', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'A high-repeat, low-risk workflow with a clear review owner', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Anything that removes all human review', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'A tool nobody needs but everyone wants to try', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-open-4',
        type: 'open',
        text: 'What guardrail would make your pilot safe enough to try next week?',
        facilitatorNote: 'Guide answers toward review checkpoints, source requirements, client-data boundaries, escalation triggers, and versioned templates.',
        placeholder: 'Example: no client-facing output without source links and a planner review...',
        options: [],
        timeLimit: 120,
      },
      {
        id: 'pi-choice-4',
        type: 'choice',
        text: 'A human must stay firmly in the loop when the AI output affects...',
        facilitatorNote: 'Make this practical: advice, spend, reputation, policy, legal/commercial risk, or anything that could be presented as agency judgement.',
        options: [
          { id: 'o1', text: 'Client advice, spend, risk, or reputation', color: COLORS[0], isCorrect: true },
          { id: 'o2', text: 'Only spelling and grammar', color: COLORS[1], isCorrect: false },
          { id: 'o3', text: 'Only internal brainstorming', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Nothing, if the AI sounds senior enough', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-open-5',
        type: 'open',
        text: 'What is one YoungShand workflow or template you would improve after this session?',
        facilitatorNote: 'Close with commitments. Cluster responses into quick wins, reusable skills, and things that need governance before testing.',
        placeholder: 'One specific process, template, prompt, checklist, or client workflow...',
        options: [],
        timeLimit: 90,
      },
    ],
  },
  {
    id: 'youngshand-media-skills-lab',
    title: 'YoungShand Media Skills Lab',
    description: 'A practical game flow for identifying useful media-planning skills, guardrails, and test cases.',
    createdAt: '2026-05-20T00:00:00.000Z',
    questions: [
      {
        id: 'ms-open-1',
        type: 'open',
        text: 'Where does the current media planning process lose the most time?',
        facilitatorNote: 'Ask for real friction, not generic AI ideas. You want repeated bottlenecks the team recognises.',
        placeholder: 'Example: turning research into a briefable channel rationale...',
        options: [],
        timeLimit: 90,
      },
      {
        id: 'ms-choice-1',
        type: 'choice',
        text: 'A useful agency AI skill is best described as...',
        facilitatorNote: 'Frame skills as repeatable workflows, not magic prompts. The value is in inputs, steps, checks, and reusable output shape.',
        options: [
          { id: 'o1', text: 'A clever one-line prompt saved in a document', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'A repeatable workflow with inputs, steps, checks, and output format', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'A chatbot that answers anything without context', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'A replacement for planner judgement', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-open-2',
        type: 'open',
        text: 'What inputs would a reliable media planning skill need before it runs?',
        facilitatorNote: 'Listen for brief, objective, budget, market, audience, channel history, constraints, benchmarks, and source files.',
        placeholder: 'Client objective, budget range, market, audience, channel history...',
        options: [],
        timeLimit: 120,
      },
      {
        id: 'ms-choice-2',
        type: 'choice',
        text: 'Which output is easiest to trust in client work?',
        facilitatorNote: 'Use this to separate polished prose from usable decision support.',
        options: [
          { id: 'o1', text: 'A structured recommendation with evidence and caveats', color: COLORS[0], isCorrect: true },
          { id: 'o2', text: 'A long paragraph with no sources', color: COLORS[1], isCorrect: false },
          { id: 'o3', text: 'A definitive answer that hides uncertainty', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'A list of trendy tactics with no client context', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-open-3',
        type: 'open',
        text: 'What checks would you build into the skill before anything reaches a client?',
        facilitatorNote: 'Draw out proof checks, source checks, data privacy checks, consistency checks, and owner sign-off.',
        placeholder: 'Example: source links required, planner review, client-data boundary, budget sanity check...',
        options: [],
        timeLimit: 120,
      },
      {
        id: 'ms-choice-3',
        type: 'choice',
        text: 'The best way to test a new skill is...',
        facilitatorNote: 'Anchor the testing mindset: compare against a known past brief or known human output before using it live.',
        options: [
          { id: 'o1', text: 'Run it on a past brief and compare against the human process', color: COLORS[0], isCorrect: true },
          { id: 'o2', text: 'Use it live with the biggest client first', color: COLORS[1], isCorrect: false },
          { id: 'o3', text: 'Only test whether the writing sounds good', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Skip testing if the demo looks impressive', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-open-4',
        type: 'open',
        text: 'Name one reusable media skill YoungShand should build first.',
        facilitatorNote: 'Cluster ideas by repeatability and risk. Pick one or two realistic candidates for a first pilot.',
        placeholder: 'Example: competitive scan summariser, brief-to-channel rationale, reporting narrative checker...',
        options: [],
        timeLimit: 90,
      },
      {
        id: 'ms-choice-4',
        type: 'choice',
        text: 'A skill should be paused or escalated when...',
        facilitatorNote: 'Keep this practical and memorable. A skill that lacks proof, violates policy, or carries high consequence needs a human decision.',
        options: [
          { id: 'o1', text: 'It lacks evidence, conflicts with policy, or the risk is high', color: COLORS[0], isCorrect: true },
          { id: 'o2', text: 'It takes more than ten seconds to run', color: COLORS[1], isCorrect: false },
          { id: 'o3', text: 'It asks for more context', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'It returns a table instead of a paragraph', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-open-5',
        type: 'open',
        text: 'What would Duncan need to see to call this skill useful?',
        facilitatorNote: 'Close on success criteria: time saved, better quality, fewer review loops, safer handoff, repeatability, or measurable client usefulness.',
        placeholder: 'A useful skill would prove itself by...',
        options: [],
        timeLimit: 90,
      },
    ],
  },
];
