import { Quiz } from '@/store/useQuizStore';

const COLORS = ['bg-red-500', 'bg-blue-500', 'bg-yellow-500', 'bg-green-500'];

export const YOUNGSHAND_WORKSHOP_PACKS: Quiz[] = [
  {
    id: 'youngshand-prove-it-sprint',
    title: 'YoungShand Prove-It Sprint',
    description: 'A sharper workshop quiz on evidence, judgement, and using AI safely in agency decisions.',
    createdAt: '2026-05-20T00:00:00.000Z',
    questions: [
      {
        id: 'pi-choice-1',
        type: 'choice',
        text: 'Which YoungShand AI use case needs the strongest proof layer before it is shared?',
        facilitatorNote: 'Use this as the warm-up. Separate low-risk drafting from work that affects spend, advice, or client confidence.',
        options: [
          { id: 'o1', text: 'Checking spelling in an internal note', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Suggesting a spend recommendation for a client plan', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Drafting alternate workshop names', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Summarising a public blog post for personal reading', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-choice-2',
        type: 'choice',
        text: 'A useful proof layer for an AI recommendation should mostly...',
        facilitatorNote: 'Reinforce that AI output needs a trail: sources, assumptions, criteria, and a clear handoff to human judgement.',
        options: [
          { id: 'o1', text: 'Sound confident and use polished wording', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Show sources, assumptions, criteria, and limits', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Avoid disagreement so the answer is clean', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Hide caveats so the recommendation feels senior', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-choice-3',
        type: 'choice',
        text: 'Which decision is best shaped for AI to help prove this week?',
        facilitatorNote: 'Good AI proof tasks are specific decisions, not generic topics.',
        options: [
          { id: 'o1', text: 'What is the future of media?', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Meta vs TikTok for this audience, objective, and budget', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Make the strategy sound more senior', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Tell us something interesting about the category', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-choice-4',
        type: 'choice',
        text: 'If an AI answer gives one confident recommendation with no assumptions, what is the next move?',
        facilitatorNote: 'This is the core behaviour shift: challenge the output before it enters client or planning work.',
        options: [
          { id: 'o1', text: 'Ask for evidence, assumptions, and alternatives', color: COLORS[0], isCorrect: true },
          { id: 'o2', text: 'Paste it into the deck and tighten the wording', color: COLORS[1], isCorrect: false },
          { id: 'o3', text: 'Ask again until the answer agrees with the plan', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Remove caveats so the answer feels decisive', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-choice-5',
        type: 'choice',
        text: 'What makes a generated source-backed answer still risky?',
        facilitatorNote: 'RAG and citations help, but they do not remove the need to test source quality, relevance, freshness, and interpretation.',
        options: [
          { id: 'o1', text: 'The answer includes too many bullet points', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'The sources may be weak, stale, cherry-picked, or misread', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'The answer is longer than the prompt', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'The model used a table instead of prose', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 35,
      },
      {
        id: 'pi-choice-6',
        type: 'choice',
        text: 'Which prompt is most likely to produce useful, provable AI output?',
        facilitatorNote: 'Push toward role, context, evidence requirements, decision criteria, uncertainty, and output format.',
        options: [
          { id: 'o1', text: 'Tell me the best media channels', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Role, context, evidence rules, assumptions, and decision criteria', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Write something smarter than our current version', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Give one answer only and do not include caveats', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 35,
      },
      {
        id: 'pi-choice-7',
        type: 'choice',
        text: 'The best first AI pilot for an agency team is usually...',
        facilitatorNote: 'Push toward low-risk, repeatable work first. A good pilot should be visible enough to learn from, but not dangerous if it fails.',
        options: [
          { id: 'o1', text: 'The most complex client strategy problem available', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'A repeatable workflow with a clear review owner', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Anything that removes all human review', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'A flashy demo with no quality benchmark', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-choice-8',
        type: 'choice',
        text: 'Which guardrail makes an AI pilot safer to try next week?',
        facilitatorNote: 'Guide the discussion toward review checkpoints, source requirements, data boundaries, and escalation triggers.',
        options: [
          { id: 'o1', text: 'No source links, because that slows the team down', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Planner review, source links, and approved data boundaries', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Only using the AI when nobody is watching', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Letting the AI decide when it needs review', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-choice-9',
        type: 'choice',
        text: 'A human must stay firmly in the loop when the AI output affects...',
        facilitatorNote: 'Make this practical: advice, spend, reputation, policy, legal/commercial risk, or anything that could be presented as agency judgement.',
        options: [
          { id: 'o1', text: 'Client advice, spend, risk, or reputation', color: COLORS[0], isCorrect: true },
          { id: 'o2', text: 'Only spelling and grammar', color: COLORS[1], isCorrect: false },
          { id: 'o3', text: 'Only internal brainstorming', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Nothing, if the AI sounds senior enough', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'pi-choice-10',
        type: 'choice',
        text: 'What is the strongest follow-up after this training?',
        facilitatorNote: 'Close with a practical next step: one workflow, one owner, one test case, and one review standard.',
        options: [
          { id: 'o1', text: 'Tell everyone to use AI more often and see what happens', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Pick one workflow, define checks, and test it on a past brief', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Buy another tool before deciding the process', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Keep all prompts personal so nobody has to maintain them', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
    ],
  },
  {
    id: 'youngshand-media-skills-lab',
    title: 'YoungShand Media Skills Lab',
    description: 'A sharper quiz on reusable media-planning skills, test design, and safe rollout.',
    createdAt: '2026-05-20T00:00:00.000Z',
    questions: [
      {
        id: 'ms-choice-1',
        type: 'choice',
        text: 'Where is AI most useful first in a media planning workflow?',
        facilitatorNote: 'Point the group toward repeatable friction, not high-risk judgement replacement.',
        options: [
          { id: 'o1', text: 'Replacing the planner who owns the recommendation', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'A structured first-pass rationale from repeatable research', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Approving the final client budget automatically', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Skipping the brief because the AI can guess it', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-choice-2',
        type: 'choice',
        text: 'A useful agency AI skill is best described as...',
        facilitatorNote: 'Frame skills as repeatable workflows, not magic prompts. The value is in inputs, steps, checks, and reusable output shape.',
        options: [
          { id: 'o1', text: 'A clever one-line prompt saved in a document', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'A repeatable workflow with inputs, steps, checks, and output format', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'A chatbot that answers anything without context', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'A replacement for planner judgement', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-choice-3',
        type: 'choice',
        text: 'Which input set would make a media planning skill most reliable?',
        facilitatorNote: 'Listen for brief, objective, budget, market, audience, history, constraints, benchmarks, and source files.',
        options: [
          { id: 'o1', text: 'Client name and a rough vibe', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Objective, budget, audience, history, constraints, and benchmarks', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Only the channel the client already likes', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'A screenshot of last month\'s deck with no context', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 35,
      },
      {
        id: 'ms-choice-4',
        type: 'choice',
        text: 'Which output is easiest to trust in client work?',
        facilitatorNote: 'Use this to separate polished prose from usable decision support.',
        options: [
          { id: 'o1', text: 'A structured recommendation with evidence and caveats', color: COLORS[0], isCorrect: true },
          { id: 'o2', text: 'A long paragraph with no sources', color: COLORS[1], isCorrect: false },
          { id: 'o3', text: 'A definitive answer that hides uncertainty', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'A list of trendy tactics with no client context', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-choice-5',
        type: 'choice',
        text: 'Which check should happen before AI-assisted planning work reaches a client?',
        facilitatorNote: 'Draw out proof checks, source checks, data privacy checks, consistency checks, and owner sign-off.',
        options: [
          { id: 'o1', text: 'Only check whether the wording feels confident', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Source, privacy, consistency, and owner sign-off checks', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Ask the AI whether it is sure', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Remove the caveats so the answer feels cleaner', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-choice-6',
        type: 'choice',
        text: 'The best way to test a new skill is...',
        facilitatorNote: 'Anchor the testing mindset: compare against a known past brief or known human output before using it live.',
        options: [
          { id: 'o1', text: 'Run it on a past brief and compare against the human process', color: COLORS[0], isCorrect: true },
          { id: 'o2', text: 'Use it live with the biggest client first', color: COLORS[1], isCorrect: false },
          { id: 'o3', text: 'Only test whether the writing sounds good', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'Skip testing if the demo looks impressive', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-choice-7',
        type: 'choice',
        text: 'Which reusable media skill is the best first pilot candidate?',
        facilitatorNote: 'Cluster ideas by repeatability and risk. Pick a realistic candidate with clear input and review needs.',
        options: [
          { id: 'o1', text: 'Autonomous budget allocator with no human approval', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Competitive scan summariser with public sources', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'Tool that writes every client strategy from scratch', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'A bot that replaces the planning meeting', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-choice-8',
        type: 'choice',
        text: 'When does a prompt become a skill rather than just a saved instruction?',
        facilitatorNote: 'A skill should have consistent inputs, workflow steps, quality gates, failure modes, and output conventions.',
        options: [
          { id: 'o1', text: 'When it is copied into a nicer document', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'When it defines inputs, checks, failure modes, and outputs', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'When it uses more technical language', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'When only one person knows how to run it', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 35,
      },
      {
        id: 'ms-choice-9',
        type: 'choice',
        text: 'A skill should be paused or escalated when...',
        facilitatorNote: 'Keep this practical and memorable. A skill that lacks proof, violates policy, or carries high consequence needs a human decision.',
        options: [
          { id: 'o1', text: 'It lacks evidence, conflicts with policy, or the risk is high', color: COLORS[0], isCorrect: true },
          { id: 'o2', text: 'It takes more than ten seconds to run', color: COLORS[1], isCorrect: false },
          { id: 'o3', text: 'It asks for more context', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'It returns a table instead of a paragraph', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
      {
        id: 'ms-choice-10',
        type: 'choice',
        text: 'What would Duncan most likely need to see to call a skill useful?',
        facilitatorNote: 'Close on success criteria: time saved, better quality, fewer review loops, safer handoff, repeatability, or measurable client usefulness.',
        options: [
          { id: 'o1', text: 'A fun demo that looks impressive once', color: COLORS[0], isCorrect: false },
          { id: 'o2', text: 'Time saved, better quality, safer handoff, fewer review loops', color: COLORS[1], isCorrect: true },
          { id: 'o3', text: 'A long list of possible tools', color: COLORS[2], isCorrect: false },
          { id: 'o4', text: 'A prompt nobody else can understand', color: COLORS[3], isCorrect: false },
        ],
        timeLimit: 30,
      },
    ],
  },
];
