'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { getSocket } from '@/lib/socket';
import { useQuizStore, Question } from '@/store/useQuizStore';
import { Plus, Play, Trash2 } from 'lucide-react';

const DEFAULT_QUESTIONS: Question[] = [
  { id: 'q1', text: 'What does AI stand for?', options: [{ id: 'o1', text: 'Artificial Intelligence', color: 'bg-red-500', isCorrect: true }, { id: 'o2', text: 'Automated Input', color: 'bg-blue-500', isCorrect: false }, { id: 'o3', text: 'Algorithmic Iteration', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'Advanced Interface', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q2', text: 'Which of these is a type of Machine Learning?', options: [{ id: 'o1', text: 'Supervised Learning', color: 'bg-red-500', isCorrect: true }, { id: 'o2', text: 'Magical Learning', color: 'bg-blue-500', isCorrect: false }, { id: 'o3', text: 'Random Learning', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'Manual Learning', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q3', text: 'What is a Neural Network inspired by?', options: [{ id: 'o1', text: 'Spider Webs', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'The Human Brain', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'Computer Circuits', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'Traffic Systems', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q4', text: 'What does NLP stand for in AI?', options: [{ id: 'o1', text: 'Natural Language Processing', color: 'bg-red-500', isCorrect: true }, { id: 'o2', text: 'New Learning Protocol', color: 'bg-blue-500', isCorrect: false }, { id: 'o3', text: 'Neural Logic Program', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'Network Level Processing', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q5', text: 'Which AI system is famous for beating a human champion at Go?', options: [{ id: 'o1', text: 'Deep Blue', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'AlphaGo', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'Watson', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'ChatGPT', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q6', text: 'What is the term for an AI that can perform any intellectual task a human can?', options: [{ id: 'o1', text: 'Narrow AI', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'General AI (AGI)', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'Super AI', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'Basic AI', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q7', text: 'What is a "bot"?', options: [{ id: 'o1', text: 'A hardware robot', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'A software application that runs automated tasks', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'A type of virus', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'A database', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q8', text: 'Which company created ChatGPT?', options: [{ id: 'o1', text: 'Google', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'Meta', color: 'bg-blue-500', isCorrect: false }, { id: 'o3', text: 'OpenAI', color: 'bg-yellow-500', isCorrect: true }, { id: 'o4', text: 'Microsoft', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q9', text: 'What is "training data"?', options: [{ id: 'o1', text: 'Data used to test an AI', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'Data used to teach a machine learning model', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'Data generated by an AI', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'Corrupted data', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q10', text: 'What is a "hallucination" in the context of LLMs?', options: [{ id: 'o1', text: 'When the AI sees images', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'When the AI generates false or illogical information', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'When the AI crashes', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'When the AI becomes sentient', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q11', text: 'What does LLM stand for?', options: [{ id: 'o1', text: 'Large Language Model', color: 'bg-red-500', isCorrect: true }, { id: 'o2', text: 'Logical Learning Machine', color: 'bg-blue-500', isCorrect: false }, { id: 'o3', text: 'Linear Language Matrix', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'Low Level Memory', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q12', text: 'Which of these is NOT a common use of AI today?', options: [{ id: 'o1', text: 'Image recognition', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'Language translation', color: 'bg-blue-500', isCorrect: false }, { id: 'o3', text: 'Time travel', color: 'bg-yellow-500', isCorrect: true }, { id: 'o4', text: 'Recommendation systems', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q13', text: 'What is "Computer Vision"?', options: [{ id: 'o1', text: 'A monitor display', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'AI that enables computers to understand images and video', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'A VR headset', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'A type of glasses', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q14', text: 'What is the Turing Test designed to evaluate?', options: [{ id: 'o1', text: 'A computer\'s processing speed', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'A machine\'s ability to exhibit intelligent behavior equivalent to a human', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'A robot\'s physical strength', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'A program\'s memory capacity', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q15', text: 'What is "Deep Learning"?', options: [{ id: 'o1', text: 'Learning underwater', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'A subset of ML based on artificial neural networks with multiple layers', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'Memorizing large books', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'A philosophical AI', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q16', text: 'Which of these is an example of generative AI?', options: [{ id: 'o1', text: 'A spam filter', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'A chess engine', color: 'bg-blue-500', isCorrect: false }, { id: 'o3', text: 'DALL-E creating an image', color: 'bg-yellow-500', isCorrect: true }, { id: 'o4', text: 'A calculator', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q17', text: 'What is a "prompt"?', options: [{ id: 'o1', text: 'A quick response', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'The input or instruction given to an AI model', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'An error message', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'A type of algorithm', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q18', text: 'What does "bias" in AI refer to?', options: [{ id: 'o1', text: 'The AI having personal feelings', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'Systematic errors in AI output due to prejudiced assumptions in training data', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'The AI preferring certain users', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'A hardware defect', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q19', text: 'What is an algorithm?', options: [{ id: 'o1', text: 'A type of math problem', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'A set of instructions or rules for a computer to follow', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'A computer virus', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'A hardware component', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 },
  { id: 'q20', text: 'Which of these fields heavily uses AI for predictive text and autocorrect?', options: [{ id: 'o1', text: 'Robotics', color: 'bg-red-500', isCorrect: false }, { id: 'o2', text: 'Natural Language Processing', color: 'bg-blue-500', isCorrect: true }, { id: 'o3', text: 'Computer Vision', color: 'bg-yellow-500', isCorrect: false }, { id: 'o4', text: 'Expert Systems', color: 'bg-green-500', isCorrect: false }], timeLimit: 20 }
];

export default function HostDashboard() {
  const router = useRouter();
  const { quizzes, deleteQuiz } = useQuizStore();
  const [isCreating, setIsCreating] = useState(false);

  const handleCreateGame = (questions: Question[]) => {
    setIsCreating(true);
    const socket = getSocket();
    
    socket.emit('create_game', questions);
    
    socket.once('game_created', (pin: string) => {
      router.push(`/host/lobby/${pin}`);
    });
  };

  return (
    <main className="min-h-screen bg-gray-50 p-4 md:p-8">
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-between items-center mb-12">
          <h1 className="text-3xl font-bold text-gray-900">Host Dashboard</h1>
          <button 
            onClick={() => router.push('/')}
            className="text-gray-500 hover:text-gray-900 font-medium transition-colors"
          >
            Back to Home
          </button>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-8">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-semibold text-gray-900">Your Quizzes</h2>
            <button
              onClick={() => router.push('/create')}
              className="flex items-center gap-2 px-4 py-2 bg-indigo-50 text-indigo-600 hover:bg-indigo-100 font-bold rounded-xl transition-colors"
            >
              <Plus className="w-5 h-5" />
              Create New
            </button>
          </div>
          
          <div className="grid gap-6">
            {/* Default Quiz */}
            <div className="border border-gray-200 rounded-xl p-6 flex justify-between items-center hover:border-indigo-300 transition-colors group">
              <div>
                <h3 className="text-xl font-bold text-gray-900 mb-2">AI Concepts Basics</h3>
                <p className="text-gray-500">{DEFAULT_QUESTIONS.length} Questions • 20s per question</p>
              </div>
              <button
                onClick={() => handleCreateGame(DEFAULT_QUESTIONS)}
                disabled={isCreating}
                className="flex items-center gap-2 px-8 py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl shadow-md transition-all active:scale-95 disabled:opacity-70"
              >
                <Play className="w-5 h-5" />
                {isCreating ? 'Creating...' : 'Host'}
              </button>
            </div>

            {/* Custom Quizzes */}
            {quizzes.map((quiz) => (
              <div key={quiz.id} className="border border-gray-200 rounded-xl p-6 flex justify-between items-center hover:border-indigo-300 transition-colors group">
                <div>
                  <h3 className="text-xl font-bold text-gray-900 mb-2">{quiz.title}</h3>
                  <p className="text-gray-500 mb-1">{quiz.description}</p>
                  <p className="text-sm text-gray-400">{quiz.questions.length} Questions</p>
                </div>
                <div className="flex items-center gap-3">
                  <button
                    onClick={() => deleteQuiz(quiz.id)}
                    className="p-3 text-red-500 hover:bg-red-50 rounded-xl transition-colors opacity-0 group-hover:opacity-100"
                    title="Delete Quiz"
                  >
                    <Trash2 className="w-5 h-5" />
                  </button>
                  <button
                    onClick={() => handleCreateGame(quiz.questions)}
                    disabled={isCreating}
                    className="flex items-center gap-2 px-8 py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl shadow-md transition-all active:scale-95 disabled:opacity-70"
                  >
                    <Play className="w-5 h-5" />
                    Host
                  </button>
                </div>
              </div>
            ))}
            
            {quizzes.length === 0 && (
              <div 
                onClick={() => router.push('/create')}
                className="border-2 border-dashed border-gray-200 rounded-xl p-8 text-center text-gray-500 hover:bg-gray-50 hover:border-indigo-300 hover:text-indigo-600 transition-colors cursor-pointer font-medium"
              >
                + Create your first custom quiz
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
